sudo: required
services:
    - docker

before_install:
    - docker build -t infine/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true infine/react-test npm run test

after_success:
    - docker build -t infine/multi-client ./client
    - docker build -t infine/multi-server ./server
    - docker build -t infine/multi-worker ./worker
    - docker build -t infine/multi-nginx ./nginx

# Log in to docker cli

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take those images and push them to docker hub

    - docker push infine/multi-client 
    - docker push infine/multi-server 
    - docker push infine/multi-worker 
    - docker push infine/multi-nginx 
